import stix2
import re

for obj in bundle.objects:
    if obj == threat_actor:
        print("------------------")
        print("== THREAT ACTOR ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Threat Actor Types: {str(obj.threat_actor_types)}")
        print(f"Roles: {str(obj.roles)}")
        print(f"Goals: {str(obj.goals)}")
        print(f"Sophistication: {obj.sophistication}")
        print(f"Resource Level: {obj.resource_level}")
        print(f"Primary Motivation: {obj.primary_motivation}")
        print(f"Secondary Motivations: {str(obj.secondary_motivations)}")

    elif obj == identity1:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Identity Class: {obj.identity_class}")

    elif obj == identity2:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Identity Class: {obj.identity_class}")

    elif obj == attack_pattern1:
        print("------------------")
        print("== ATTACK PATTERN ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Type: {obj.type}")
        print(f"External References: {str(obj.external_references)}")

    elif obj == attack_pattern2:
        print("------------------")
        print("== ATTACK PATTERN ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Type: {obj.type}")
        print(f"External References: {str(obj.external_references)}")


    elif obj == campaign1:
        print("------------------")
        print("== CAMPAIGN ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.description}")
        print(f"Type: {obj.type}")
        print(f"Aliases: {str(obj.aliases)}")
        print(f"First Seen: {str(obj.first_seen)}")
        print(f"Objective: {obj.objective}")

    elif obj == campaign2:
        print("------------------")
        print("== CAMPAIGN ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.description}")
        print(f"Type: {obj.type}")
        print(f"Aliases: {str(obj.aliases)}")
        print(f"First Seen: {str(obj.first_seen)}")
        print(f"Objective: {obj.objective}")

    elif obj == intrusionset:
        print("------------------")
        print("== INTRUSION SET ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.name}")
        print(f"Type: {obj.type}")
        print(f"Aliases: {str(obj.aliases)}")
        print(f"First Seen: {str(obj.first_seen)}")
        print(f"Goals: {str(obj.goals)}")
        print(f"Resource Level: {obj.resource_level}")
        print(f"Primary Motivation: {obj.primary_motivation}")
        print(f"Secondary Motivations: {str(obj.secondary_motivations)}")

    elif re.search('relationship*', str(obj)):
        print("------------------")
        print("== RELATIONSHIP ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Type: {obj.type}")
        print(f"Relationship Type: {obj.relationship_type}")
        print(f"Source Ref: {obj.source_ref}")
        print(f"Target Ref: {obj.target_ref}")
