from stix2.v21 import (Bundle)

for obj in bundle.objects:
    if obj == threat_actor:
        print("------------------")
        print("== THREAT ACTOR ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.description}")
        print(f"Threat Actor Types: {str(obj.threat_actor_types)}")
        print(f"Aliases: {str(obj.aliases)}")
        print(f"Roles: {str(obj.roles)}")
        print(f"Goals: {str(obj.goals)}")
        print(f"Sophistication: {obj.sophistication}")
        print(f"Resource Level: {obj.resource_level}")
        print(f"Primary Motivation: {obj.primary_motivation}")

    elif obj == identity:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.description}")
        print(f"Identity Class: {obj.identity_class}")
        print(f"Contact Information: {obj.contact_information}")

    elif obj == relationship:
        print("------------------")
        print("== RELATIONSHIP ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Type: {obj.type}")
        print(f"Relationship Type: {obj.relationship_type}")
        print(f"Source Ref: {obj.source_ref}")
        print(f"Target Ref: {obj.target_ref}")
