from stix2.v21 import (Bundle)

for obj in bundle.objects:
    if obj == identityPym:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Identity Class: {obj.identity_class}")
        print(f"Sectors: {str(obj.sectors)}")
        print(f"Contact Information: {obj.contact_information}")

    elif obj == identityOscorp:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Identity Class: {obj.identity_class}")
        print(f"Sectors: {str(obj.sectors)}")
        print(f"Contact Information: {obj.contact_information}")

    elif obj == malware:
        print("------------------")
        print("== MALWARE ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Type: {obj.type}")
        print(f"Malware Types: {str(obj.malware_types)}")
        print(f"Is Family:{str(obj.is_family)}")


    elif obj == observedDataFile:
        print("------------------")
        print("== OBSERVED DATA ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Created by Ref: {obj.created_by_ref}")
        print(f"First Observed: {str(obj.first_observed)}")
        print(f"Last Observed: {str(obj.last_observed)}")
        print(f"Number Observed: {str(obj.number_observed)}")
        print(f"Object Refs: {str(obj.object_refs)}")

    elif obj == observedDataRegKey:
        print("------------------")
        print("== OBSERVED DATA ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Created by Ref: {obj.created_by_ref}")
        print(f"First Observed: {str(obj.first_observed)}")
        print(f"Last Observed: {str(obj.last_observed)}")
        print(f"Number Observed: {str(obj.number_observed)}")
        print(f"Object Refs: {str(obj.object_refs)}")

    elif obj == sighting:
        print("------------------")
        print("== SIGHTING ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Type: {obj.type}")
        print(f"Created by Ref: {obj.created_by_ref}")
        print(f"First Seen: {str(obj.first_seen)}")
        print(f"Last Seen: {str(obj.last_seen)}")
        print(f"Count: {str(obj.count)}")
        print(f"Sighting of Ref: {obj.sighting_of_ref}")
        print(f"Observed Data Ref: {str(obj.observed_data_refs)}")
        print(f"Where Sighted Refs: {str(obj.where_sighted_refs)}")

    elif obj == fileMalicious:
        print("------------------")
        print("== FILE ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Type: {obj.type}")
        print(f"Hashes: {str(obj.hashes)}")
        print(f"Name: {obj.name}")
        print(f"Size: {str(obj.size)}")

    elif obj == winRegKey:
        print("------------------")
        print("== WINDOWS REGISTRY KEY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Type: {obj.type}")
        print(f"Key: {obj.key}")
