from stix2.v21 import (Bundle)

for obj in bundle.objects:
    if obj in [identityAlpha, identityBeta]:
        print("------------------")
        print("== IDENTITY ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Roles: {str(obj.roles)}")
        print(f"Identity Class: {obj.identity_class}")
        print(f"Sectors: {str(obj.sectors)}")
        print(f"Contact Information: {obj.contact_information}")

    elif obj == indicator:
        print("------------------")
        print("== INDICATOR ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Name: {obj.name}")
        print(f"Description: {obj.description}")
        print(f"Type: {obj.type}")
        print(f"Indicator Types: {str(obj.indicator_types)}")
        print(f"Pattern: {obj.pattern}")
        print(f"Pattern Type: {obj.pattern_type}")
        print(f"Valid From: {str(obj.valid_from)}")

    elif obj == sighting:
        print("------------------")
        print("== SIGHTING ==")
        print("------------------")
        print(f"ID: {obj.id}")
        print(f"Created: {str(obj.created)}")
        print(f"Modified: {str(obj.modified)}")
        print(f"Type: {obj.type}")
        print(f"Created by Ref: {obj.created_by_ref}")
        print(f"First Seen: {str(obj.first_seen)}")
        print(f"Last Seen: {str(obj.last_seen)}")
        print(f"Count: {str(obj.count)}")
        print(f"Sighting of Ref: {obj.sighting_of_ref}")
        print(f"Where Sighted Refs: {str(obj.where_sighted_refs)}")
